### ISSUE TITLE
Gringotts + Vault Support 

### ISSUE THREAD

**Issue by Adamantyte** [Nutty101/NPC-Police#1]
I'd like to see Gringotts + Vault support. I use a hard currency on my server and players use emeralds as money. The default way to store your money is in a vault, created by putting money in a chest and putting a sign saying [Vault] on it. That way, when you type /money it shows your inventory, as well as vault balance which can be used to make payments. Id like this plugin to be able to draw from a players vault so they can pay their way out of jail, without having to carry around a thousand emeralds. This can be done because there is a plugin called Catacombs that has no relation to Gringotts but is able to withdraw from a players vaults to make payments. In other words, need Gringotts support :D

**Comment by Nutty101** [comment]
Will look that one up and see how to interface with it.

**Comment by Legoman99573** [comment]
How did i get tagged?, oh well, this does sound nice ;)

**Comment by Nutty101** [comment]
Can you link me to the Gringotts you are using? Will help me figure out what links are needed

**Comment by Nutty101** [comment]
Oh lego, you had watched the original resource (Jailer) if I recall. So that's why it added you.

**Comment by Legoman99573** [comment]
Im good, this sounds like a good feature :D

**Comment by Adamantyte** [comment]
I'm using the latest version found here. https://dev.bukkit.org/projects/gringotts

**Comment by Nutty101** [comment]
Turns out the gringotts uses vault as it is. So I am going to close this one out.
