### ISSUE TITLE
NPC Attacking me with no bounty level

### ISSUE THREAD

**Issue by LadyHaley** [Nutty101/NPC-Police#10]
I'm setting this plugin up for the first time and have encountered a problem, I have no bounty but the sentinel guard keeps jailing me when I walk near them. I'm not really sure what I have done wrong here.
I configured him with these commands

> 17.01 06:24:25 [Server] INFO LadyHaley issued server command: /trait sentinel
17.01 06:25:17 [Server] INFO LadyHaley issued server command: /sentinel addtarget group:WANTEDCRIMINALS
17.01 06:25:26 [Server] INFO LadyHaley issued server command: /sentinel addtarget group:FUGITIVES
17.01 06:25:34 [Server] INFO LadyHaley issued server command: /sentinel removeignore owner 

Is this a known issue, how would i go about solving it
I'm not getting any errors in the console

**Comment by Nutty101** [comment]
Are you in the wanted or fugitives group? That would be what causes this. I would remove the groups and use the LOS setting on the NPC   /nd npc  (Click LOS) and remove target groups. My plugin will take care of the rest.

**Comment by LadyHaley** [comment]
Im not in either groups

**Comment by Nutty101** [comment]
Are you on discord? If you can hit me up on there, we could time it and I could log on and we will get it fixed.

**Comment by Nutty101** [comment]
Old, closed.
