### ISSUE TITLE
Language File Format

### ISSUE THREAD

**Issue by doitliketyler** [Nutty101/NPC-Police#11]
Hello. I would really like to customize the language file for NPC-Police with ease but in its current format that would be impossible. Could you please convert this to a manageable format?

**Comment by doitliketyler** [comment]
It would actually be nice if you did this one all your plugins.

**Comment by Nutty101** [comment]
Due to the nature of how my plugins work with clicking, etc.. It's how the formatting works. To change it would be a serious undertaking. 

What issues are you having?

**Comment by doitliketyler** [comment]
Sorry for my extremely late reply. I'm usually very responsive. I get that...I guess I'm just super spoiled with the standard color codes is all.

**Comment by Nutty101** [comment]
Closing old comment.
