### ISSUE TITLE
ZQuest Support

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [Nutty101/NPC-Police#3]
Maybe you can add ZQuest Support by contacting the dev of it? https://www.spigotmc.org/resources/zquest-feel-the-might-of-creating-1-9-1-10-1-11.18045/

**Comment by Nutty101** [comment]
Will look into that one. Have looked at it, but never really tried it. He has an API if I can recall, so shouldn't be hard at all.  Will update you on this tonight if I can.

**Comment by Nutty101** [comment]
Snagged it and am adding all the conditions into it for yah.

**Comment by xH3LLRAIZ3Rx** [comment]
ok awesome :D

**Comment by Nutty101** [comment]
ZQuest support has been removed as the plugin has not been updated.
