### ISSUE TITLE
Worldguard Region Flags Spamming messages

### ISSUE THREAD

**Issue by tpalaz** [Nutty101/NPC-Police#54]
When setting a flag to give a wanted status when enter a region, the np-af-caught message is spammed even when changing the np-af-cooldown message. In order for this to work, the following flags need to be set:
np-af = WANTED
np-af-caught = Your wanted level has increased
np-af-bounty = 2
np-af-cooldown = 1200

The "np-af-caught" flag is repeatedly spammed in chat despite the cool-down flag

**Comment by Nutty101** [comment]
Resolved. :)
