### ISSUE TITLE
Request: Item Blacklist on Inventory Taken

### ISSUE THREAD

**Issue by BrianTheStangLover** [Nutty101/NPC-Police#7]
When a player's inventory is taken on jailed and given back on escape or freed would it be possible to not return a certain item ID?

Example: Player robs by bank vault and steals the emeralds but is arrested before they can escape. They still get those emeralds back when they are released.

**Comment by Nutty101** [comment]
It would remove all emeralds from the player since I wouldn't know how many they had prior. I think a list of items to never give back would be great, though. Will work on this for you.
