### ISSUE TITLE
Npc allowed to damage target above default health levels. (more than default hearts)

### ISSUE THREAD

**Issue by Mavhill** [Nutty101/NPC-Police#9]
NPC police cannot hit players Without activation of damage enforcers in Sentinel config. With them set as you well know they cannot measure damage done and so continue to attack after release from jail. using spigot 1.11.2, sentinel 1.0.1 and latest of this plug. So to be clear:
1. With Sentinel set for damage enforcement, so they can do damage breaks Npc Police.
2. Without Sentinel sets for damage enforcement Npc cannot damage players and so cannot arrest them.

using a health plug that boosts hearts for players I believe this is related to the problem as I think the plug is not able to register damage above default health. If i slowly cause damage to a player as soon as their health is below default max the npc will then arrest the player. but before this point its like they cannot affect the player at all.

**Comment by Nutty101** [comment]
Sorry, blew out my computer so had to get a new one.  What plugin are you using for more hearts? Could play with it and see what I can see.

**Comment by Nutty101** [comment]
Hit me up on spigot with more information on this. Can re-open it once i get that.
